# Github Action for deploying new releases --> Github release and PyPI package

name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest
    name: Get configured version
    steps:
      - uses: actions/checkout@v3

      - id: version
        name: Get configured version
        run: echo "VERSION=$(grep -oE 'version = "([0-9.+]+)"' pyproject.toml | sed -E 's/.*"([0-9.]+)"/\1/g')" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.VERSION }}

  github-release:
    needs: [check-version]
    runs-on: ubuntu-latest
    name: Create Github release
    steps:
      - uses: actions/checkout@v3

      - name: Create a Github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/knot_warc-*.tar.gz
            dist/knot_warc-*.py3-none-any.whl
          tag_name: v${{ needs.version.outputs.VERSION }}
          fail_on_unmatched_files: true
          generate_release_notes: true

  pypi-package:
    needs: [check-version]
    runs-on: ubuntu-latest
    name: Create and publish pip package to PyPI
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip build

      - name: Build a Python package for pip
        run: python3 -m build

      - name: Publish as a Package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
