# Github workflow for automatic tests

name: 'Tests'

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build a pip package
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip build

      - name: Build a Python package for pip
        run: python3 -m build

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.4.5', '3.5.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    name: Pytest on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup micromamba
        run: |
          wget -O micromamba https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-linux-64
          chmod +x ./micromamba

      - name: Create and prepare Mamba/Conda environment
        run: ./micromamba create -n warc python==${{ matrix.python-version }} pytest

      - name: Run pytest
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: dpkg --compare-versions "$PYTHON_VERSION" "gt" "3.4" && ./micromamba run -n warc pytest --tb=long --full-trace --color=yes --code-highlight=yes || ./micromamba run -n warc pytest --tb=long --full-trace --color=yes
